/* auto-generated by tooling/chief-sentinel/build_chief_imports.py */
/* cleared — all data now comes from user uploads via /chief/import */

export const activity_logs: Record<string, unknown>[] = [];
export const assets: Record<string, unknown>[] = [];
export const emergency_contacts: Record<string, unknown>[] = [];
export const employee_compliance: Record<string, unknown>[] = [];
export const maintenance_events: Record<string, unknown>[] = [];
export const maintenance_plans: Record<string, unknown>[] = [];
export const organizations: Record<string, unknown>[] = [];
export const people: Record<string, unknown>[] = [];
export const permit_license_records: Record<string, unknown>[] = [];
export const reference_contacts: Record<string, unknown>[] = [];
export const suspense_items: Record<string, unknown>[] = [];
export const tank_assets: Record<string, unknown>[] = [];
export const vehicle_assets: Record<string, unknown>[] = [];
