"""
Auto-generated python-docx code from: TNDS_Client_Email_Sequences.docx
Generated by doc_to_code.py - True North Data Strategies

HOW TO RUN:
  pip install python-docx     (one-time)
  python TNDS_Client_Email_Sequences_generator.py
"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

# ============================================
# COLORS FOUND IN DOCUMENT
# ============================================
COLOR_1A3A5C = RGBColor(0x1A, 0x3A, 0x5C)  # #1A3A5C
COLOR_3D8EB9 = RGBColor(0x3D, 0x8E, 0xB9)  # #3D8EB9
COLOR_F5F9FC = RGBColor(0xF5, 0xF9, 0xFC)  # #F5F9FC

# ============================================
# CREATE DOCUMENT
# ============================================
doc = Document()

# Page setup
section = doc.sections[0]
section.page_width = 7772400
section.page_height = 10058400
section.top_margin = Inches(1.0)
section.bottom_margin = Inches(1.0)
section.left_margin = Inches(1.0)
section.right_margin = Inches(1.0)

# ============================================
# CONTENT
# ============================================
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("CLIENT EMAIL SEQUENCES")
run.bold = True
run.font.size = Pt(24.0)
run.font.color.rgb = RGBColor(0x1A, 0x3A, 0x5C)
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("Command Protocol Delivery Communications")
run.font.size = Pt(12.0)
run.font.color.rgb = RGBColor(0x3D, 0x8E, 0xB9)
doc.add_heading("OVERVIEW", level=1)
doc.add_paragraph("These email templates support the Command Protocol delivery process. Each email corresponds to a specific milestone in client engagement. Use Direction Protocol stage names when referencing the sales process.")
doc.add_paragraph("")  # Empty line
p = doc.add_paragraph()
run = p.add_run("Stage Reference: ")
run.bold = True
run = p.add_run("All emails below occur AFTER the Launch stage of the Direction Protocol.")
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_heading("EMAIL 1: Welcome and Next Steps", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("Welcome to True North - Here is What Happens Next")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("Immediately after Launch stage (contract signed, deposit received)")
doc.add_paragraph("")  # Empty line

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nWelcome to True North Data Strategies.\n\nYour deposit has been received and we are officially kicking off your\n[Command Center Build / Battle Rhythm Install]. We have completed "
# Cell (0,0) has background color: #F5F9FC

doc.add_paragraph("")  # Empty line
doc.add_heading("EMAIL 2: System Access Request", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("Quick Action Needed - System Access for [Project Name]")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("Within 2 hours of kickoff call")
doc.add_paragraph("")  # Empty line

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nGreat kickoff call. I am excited to start building your Command modules.\n\nTo begin, I need access to the following systems:\n\nSYSTEM ACCESS NEEDED:\n\n1. [System Name - e.g., Y"
# Cell (0,0) has background color: #F5F9FC

doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_heading("EMAIL 3: Weekly Progress Update", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("[Project Name] Progress Update - Week [X]")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("End of week 1, then weekly until launch")
doc.add_paragraph("")  # Empty line

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nQuick update on your Command Center Build:\n\nCOMPLETED THIS WEEK:\n- [Specific accomplishment 1]\n- [Specific accomplishment 2]\n- [Specific accomplishment 3]\n\nIN PROGRESS:\n- "
# Cell (0,0) has background color: #F5F9FC

doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_heading("EMAIL 4: Authorization Request (OAuth)", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("Action Required - Authorize Your Email (2 minutes)")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("When system is ready for OAuth connection")
doc.add_paragraph("")  # Empty line

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nYour Command modules are built and ready. Just need one quick step from you:\n\nCLICK HERE TO AUTHORIZE: [AUTH_URL]\n\nWhat you will see:\n1. Google login screen (use [their@gmail"
# Cell (0,0) has background color: #F5F9FC

doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_heading("EMAIL 5: Training Scheduled", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("[Project Name] Ready for Training")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("After successful testing, before training session")
doc.add_paragraph("")  # Empty line

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nExcellent news - your Command Center is tested and ready for training.\n\nYOUR SYSTEM:\nDashboard: [Link to their system]\nDocumentation: [Link to guide]\n\nTRAINING SESSION:\nDat"
# Cell (0,0) has background color: #F5F9FC

doc.add_paragraph("")  # Empty line
doc.add_heading("EMAIL 6: Go-Live Confirmation", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("You are Live - [Project Name] is Running")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("Immediately after training session")
doc.add_paragraph("")  # Empty line

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nCongratulations - your Command Center is officially live.\n\nYOUR RESOURCES:\n- Dashboard: [Link]\n- Training recording: [Link]\n- Documentation: [Link]\n- Support email: jacob@tr"
# Cell (0,0) has background color: #F5F9FC

doc.add_heading("EMAIL 7: Two-Week Check-In", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("Quick Check-In - How is [Project Name] Working?")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("Exactly 14 days after go-live")
doc.add_paragraph("")  # Empty line

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nYou have been using your Command Center for 2 weeks now. How is it going?\n\nSYSTEM STATS (PAST 2 WEEKS):\n- [Metric 1: e.g., 45 follow-up emails sent]\n- [Metric 2: e.g., 23 lead"
# Cell (0,0) has background color: #F5F9FC

doc.add_paragraph("")  # Empty line
doc.add_heading("EMAIL 8: Monthly Invoice", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("Invoice #[NUMBER] - [Month] Support for [Project Name]")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("1st of each month (automated via Stripe)")
doc.add_paragraph("")  # Empty line

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nYour monthly Command Partner invoice is ready:\n\nINVOICE #[NUMBER]\nAmount: $[XX].00\nDue: [Date]\nPay online: [Stripe link]\n\nWhat you are getting this month:\n- System monitor"
# Cell (0,0) has background color: #F5F9FC

doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_heading("EMAIL 9: Support Ticket Response", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("Re: [Client Subject]")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("When responding to support requests")
doc.add_paragraph("")  # Empty line

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nThanks for reaching out.\n\nISSUE:\n[Restate their problem to confirm understanding]\n\nSOLUTION:\n[What you did to fix it]\n\nTESTING:\nI have tested and confirmed it is working "
# Cell (0,0) has background color: #F5F9FC

doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_paragraph("")  # Empty line
doc.add_heading("EMAIL 10: Client Offboarding", level=2)
p = doc.add_paragraph()
run = p.add_run("Subject: ")
run.bold = True
run = p.add_run("[Project Name] Transition Plan")
p = doc.add_paragraph()
run = p.add_run("When to send: ")
run.bold = True
run = p.add_run("After receiving cancellation notice")

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "Hi [Client Name],\n\nI received your cancellation notice. Sorry to see you go.\n\nTRANSITION TIMELINE:\n- Support continues through: [30 days from notice]\n- Final invoice: [Date]\n- System handoff: ["
# Cell (0,0) has background color: #F5F9FC

doc.add_paragraph("")  # Empty line
doc.add_heading("USAGE NOTES", level=1)
doc.add_paragraph("1. Personalize: Always customize with client-specific details")
doc.add_paragraph("2. Timing: Send at the stages indicated, adjust as needed")
doc.add_paragraph("3. Tone: Match the client communication style")
doc.add_paragraph("4. Links: Replace all [LINK] placeholders with actual URLs")
doc.add_paragraph("5. Tracking: Keep a log of which emails sent when for each client")
doc.add_paragraph("")  # Empty line
doc.add_paragraph("Direction Protocol stages: IDENTIFY, ASSESS, MAP, CHART, LAUNCH")
doc.add_paragraph("Command Protocol services: Command Center Build, Battle Rhythm Install, Command Partner")
doc.add_paragraph("")  # Empty line
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("Direction Protocol gets you clarity. Command Protocol gets you control.")
run.italic = True
run.font.color.rgb = RGBColor(0x3D, 0x8E, 0xB9)
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run("That is how we turn data into direction.")
run.italic = True
run.font.color.rgb = RGBColor(0x3D, 0x8E, 0xB9)

doc.save("TNDS_Client_Email_Sequences_REBUILT.docx")
print("Created: TNDS_Client_Email_Sequences_REBUILT.docx")