"""
Auto-generated reportlab code from: TNDS_Client_Email_Sequences.docx
Generated by doc_to_code.py - True North Data Strategies

HOW TO RUN:
  pip install reportlab     (one-time)
  python TNDS_Client_Email_Sequences_pdf_generator.py
"""

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph as FlowParagraph

# ============================================
# COLORS FOUND IN DOCUMENT
# ============================================
COLOR_1A3A5C = HexColor("#1A3A5C")
COLOR_3D8EB9 = HexColor("#3D8EB9")
COLOR_F5F9FC = HexColor("#F5F9FC")

# ============================================
# CONTENT EXTRACTED FROM DOCUMENT
# ============================================
CONTENT = [
    {"type": "text", "style": "Normal", "align": "CENTER", "text": "CLIENT EMAIL SEQUENCES", "color": "#1A3A5C", "size": 24.0, "bold": True},
    {"type": "text", "style": "Normal", "align": "CENTER", "text": "Command Protocol Delivery Communications", "color": "#3D8EB9", "size": 12.0, "bold": False},
    {"type": "text", "style": "Heading 1", "align": "LEFT", "text": "OVERVIEW", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "These email templates support the Command Protocol delivery process. Each email corresponds to a specific milestone in client engagement. Use Directio", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Stage Reference: All emails below occur AFTER the Launch stage of the Direction Protocol.", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 1: Welcome and Next Steps", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: Welcome to True North - Here is What Happens Next", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: Immediately after Launch stage (contract signed, deposit received)", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  Welcome to True North Data Strategies.  Your deposit has been received and we are officially kicking off your [Command Center Build"},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 2: System Access Request", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: Quick Action Needed - System Access for [Project Name]", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: Within 2 hours of kickoff call", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  Great kickoff call. I am excited to start building your Command modules.  To begin, I need access to the following systems:  SYSTEM"},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 3: Weekly Progress Update", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: [Project Name] Progress Update - Week [X]", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: End of week 1, then weekly until launch", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  Quick update on your Command Center Build:  COMPLETED THIS WEEK: - [Specific accomplishment 1] - [Specific accomplishment 2] - [Spe"},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 4: Authorization Request (OAuth)", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: Action Required - Authorize Your Email (2 minutes)", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: When system is ready for OAuth connection", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  Your Command modules are built and ready. Just need one quick step from you:  CLICK HERE TO AUTHORIZE: [AUTH_URL]  What you will se"},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 5: Training Scheduled", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: [Project Name] Ready for Training", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: After successful testing, before training session", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  Excellent news - your Command Center is tested and ready for training.  YOUR SYSTEM: Dashboard: [Link to their system] Documentatio"},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 6: Go-Live Confirmation", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: You are Live - [Project Name] is Running", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: Immediately after training session", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  Congratulations - your Command Center is officially live.  YOUR RESOURCES: - Dashboard: [Link] - Training recording: [Link] - Docum"},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 7: Two-Week Check-In", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: Quick Check-In - How is [Project Name] Working?", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: Exactly 14 days after go-live", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  You have been using your Command Center for 2 weeks now. How is it going?  SYSTEM STATS (PAST 2 WEEKS): - [Metric 1: e.g., 45 follo"},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 8: Monthly Invoice", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: Invoice #[NUMBER] - [Month] Support for [Project Name]", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: 1st of each month (automated via Stripe)", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  Your monthly Command Partner invoice is ready:  INVOICE #[NUMBER] Amount: $[XX].00 Due: [Date] Pay online: [Stripe link]  What you "},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 9: Support Ticket Response", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: Re: [Client Subject]", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: When responding to support requests", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  Thanks for reaching out.  ISSUE: [Restate their problem to confirm understanding]  SOLUTION: [What you did to fix it]  TESTING: I h"},
    {"type": "text", "style": "Heading 2", "align": "LEFT", "text": "EMAIL 10: Client Offboarding", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Subject: [Project Name] Transition Plan", "color": None, "size": None, "bold": True},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "When to send: After receiving cancellation notice", "color": None, "size": None, "bold": True},
    {"type": "table_cell", "text": "Hi [Client Name],  I received your cancellation notice. Sorry to see you go.  TRANSITION TIMELINE: - Support continues through: [30 days from notice] "},
    {"type": "text", "style": "Heading 1", "align": "LEFT", "text": "USAGE NOTES", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "1. Personalize: Always customize with client-specific details", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "2. Timing: Send at the stages indicated, adjust as needed", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "3. Tone: Match the client communication style", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "4. Links: Replace all [LINK] placeholders with actual URLs", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "5. Tracking: Keep a log of which emails sent when for each client", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Direction Protocol stages: IDENTIFY, ASSESS, MAP, CHART, LAUNCH", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "LEFT", "text": "Command Protocol services: Command Center Build, Battle Rhythm Install, Command Partner", "color": None, "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "CENTER", "text": "Direction Protocol gets you clarity. Command Protocol gets you control.", "color": "#3D8EB9", "size": None, "bold": False},
    {"type": "text", "style": "Normal", "align": "CENTER", "text": "That is how we turn data into direction.", "color": "#3D8EB9", "size": None, "bold": False},
]

# ============================================
# GENERATE PDF
# NOTE: PDF uses absolute positioning.
# You will need to adjust Y coordinates to
# position elements where you want them.
# Y=0 is BOTTOM, Y=792 is TOP.
# ============================================
c = canvas.Canvas("TNDS_Client_Email_Sequences_REBUILT.pdf", pagesize=(612, 792))

y = 720  # Start 1 inch from top
LEFT_MARGIN = 72   # 1 inch left margin

for item in CONTENT:
    if item["type"] == "text":
        size = item["size"] or 11
        if item["style"].startswith("Heading"):
            size = 18 if "1" in item["style"] else 14
        c.setFont("Helvetica-Bold" if item["bold"] else "Helvetica", size)
        if item["color"]:
            c.setFillColor(HexColor(item["color"]))
        else:
            c.setFillColor(HexColor("#000000"))
        c.drawString(LEFT_MARGIN, y, item["text"][:80])
        y -= size + 6
    elif item["type"] == "table_cell":
        c.setFont("Helvetica", 10)
        c.setFillColor(HexColor("#000000"))
        c.drawString(LEFT_MARGIN + 10, y, item["text"][:80])
        y -= 16
    
    if y < 72:  # New page if near bottom
        c.showPage()
        y = 720

c.save()
print("Created: TNDS_Client_Email_Sequences_REBUILT.pdf")