/**
 * Auto-generated docx-js code from: Pipeline_Flyer.docx
 * Generated by doc_to_code.py - True North Data Strategies
 *
 * HOW TO RUN:
 *   npm install docx     (one-time)
 *   node Pipeline_Flyer_generator.js
 */

const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  AlignmentType, BorderStyle, WidthType, ShadingType, VerticalAlign,
  HeadingLevel, PageBreak
} = require("docx");

// ============================================
// COLORS FOUND IN DOCUMENT
// ============================================
const COLOR_0 = "0F2236";  // #0F2236
const COLOR_1 = "1A3A5C";  // #1A3A5C
const COLOR_2 = "3D8EB9";  // #3D8EB9
const COLOR_3 = "6B8AA5";  // #6B8AA5
const COLOR_4 = "A0B8CC";  // #A0B8CC
const COLOR_5 = "C8DAE8";  // #C8DAE8
const COLOR_6 = "FFFFFF";  // #FFFFFF

// ============================================
// FONTS FOUND IN DOCUMENT
// ============================================
const FONT_ARIAL = "Arial";

// ============================================
// HELPERS
// ============================================
const noBorder = { style: BorderStyle.NONE, size: 0, color: "FFFFFF" };
const noBorders = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };
const thinBorder = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const thinBorders = { top: thinBorder, bottom: thinBorder, left: thinBorder, right: thinBorder };

// ============================================
// BUILD DOCUMENT
// ============================================
const doc = new Document({
  styles: {
    default: {
      document: { run: { font: "Arial", size: 22 } }
    }
  },
  sections: [{
    properties: {
      page: {
        size: { width: 12240, height: 15840 },
        margin: { top: 0, right: 0, bottom: 0, left: 0 }
      }
    },
    children: [
      new Table({  // 1 rows x 1 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [12240],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "3D8EB9", type: ShadingType.CLEAR },
                width: { size: 12240, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({ children: [new TextRun({ text: "" })] }),  // ""
                ]
              }),
            ]
          }),
        ]
      }),
      new Table({  // 1 rows x 1 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [12240],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "1A3A5C", type: ShadingType.CLEAR },
                width: { size: 12240, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({
                    children: [new TextRun({ text: "TRUE NORTH DATA STRATEGIES  |  SBA-Certified SDVOSB  |  Colorado Springs, CO", font: "Arial", size: 16, color: "A0B8CC" })]
                  }),  // "TRUE NORTH DATA STRATEGIES  |  SBA-Certified SDVOS..."
                ]
              }),
            ]
          }),
        ]
      }),
      new Table({  // 1 rows x 1 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [12240],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "1A3A5C", type: ShadingType.CLEAR },
                width: { size: 12240, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({ children: [new TextRun({ text: "PIPELINE", font: "Arial", size: 72, bold: true, color: "FFFFFF" })] }),  // "PIPELINE"
                  new Paragraph({ spacing: { before: 200 }, children: [new TextRun({ text: "" })] }),  // ""
                  new Paragraph({ children: [new TextRun({ text: "Your business already has the answers.", font: "Arial", size: 28, color: "C8DAE8" })] }),  // "Your business already has the answers."
                  new Paragraph({ children: [new TextRun({ text: "Pipeline connects them.", font: "Arial", size: 28, bold: true, color: "FFFFFF" })] }),  // "Pipeline connects them."
                  new Paragraph({
                    children: [new TextRun({ text: "Pipeline connects your scattered business tools — email, spreadsheets, databases, CRMs, and documents — into one central hub where anyone on your team can ask questions in plain English and get answers instantly.", font: "Arial", size: 22, color: "A0B8CC" })]
                  }),  // "Pipeline connects your scattered business tools — ..."
                ]
              }),
            ]
          }),
        ]
      }),
      new Table({  // 1 rows x 1 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [12240],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "1A3A5C", type: ShadingType.CLEAR },
                width: { size: 12240, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({ children: [new TextRun({ text: "SOUND FAMILIAR?", font: "Arial", size: 22, bold: true, color: "3D8EB9" })] }),  // "SOUND FAMILIAR?"
                ]
              }),
            ]
          }),
        ]
      }),
      new Table({  // 1 rows x 3 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [4080, 4080, 4080],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "1A3A5C", type: ShadingType.CLEAR },
                width: { size: 4080, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({ children: [new TextRun({ text: "Information is everywhere", font: "Arial", size: 22, bold: true, color: "FFFFFF" })] }),  // "Information is everywhere"
                  new Paragraph({
                    children: [new TextRun({ text: "Client details in email. Job info in a spreadsheet. Financials in one app. Schedules in another. Nothing talks to each other.", font: "Arial", size: 18, color: "A0B8CC" })]
                  }),  // "Client details in email. Job info in a spreadsheet..."
                ]
              }),
              new TableCell({
                borders: thinBorders, shading: { fill: "1A3A5C", type: ShadingType.CLEAR },
                width: { size: 4080, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({ children: [new TextRun({ text: "One person knows everything", font: "Arial", size: 22, bold: true, color: "FFFFFF" })] }),  // "One person knows everything"
                  new Paragraph({
                    children: [new TextRun({ text: "The owner or office manager is the human search engine. If they’re gone, the team is stuck. Nobody can take a day off.", font: "Arial", size: 18, color: "A0B8CC" })]
                  }),  // "The owner or office manager is the human search en..."
                ]
              }),
              new TableCell({
                borders: thinBorders, shading: { fill: "1A3A5C", type: ShadingType.CLEAR },
                width: { size: 4080, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({
                    children: [new TextRun({ text: "You can’t see your own business", font: "Arial", size: 22, bold: true, color: "FFFFFF" })]
                  }),  // "You can’t see your own business"
                  new Paragraph({
                    children: [new TextRun({ text: "The data exists, but you can’t get a straight answer without digging through five tools and three people.", font: "Arial", size: 18, color: "A0B8CC" })]
                  }),  // "The data exists, but you can’t get a straight answ..."
                ]
              }),
            ]
          }),
        ]
      }),
      new Table({  // 1 rows x 1 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [12240],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "1A3A5C", type: ShadingType.CLEAR },
                width: { size: 12240, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({ children: [new TextRun({ text: "" })] }),  // ""
                ]
              }),
            ]
          }),
        ]
      }),
      new Table({  // 1 rows x 1 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [12240],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "1A3A5C", type: ShadingType.CLEAR },
                width: { size: 12240, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({ children: [new TextRun({ text: "WHAT YOU GET", font: "Arial", size: 22, bold: true, color: "3D8EB9" })] }),  // "WHAT YOU GET"
                  new Paragraph({
                    children: [new TextRun({ text: "—  ", font: "Arial", size: 22, bold: true, color: "3D8EB9" }), new TextRun({ text: "One hub for all your business data — no more app-hopping", font: "Arial", size: 20, color: "C8DAE8" })]
                  }),  // "—  One hub for all your business data — no more ap..."
                  new Paragraph({
                    children: [new TextRun({ text: "—  ", font: "Arial", size: 22, bold: true, color: "3D8EB9" }), new TextRun({ text: "Plain English search — no training, no tech skills needed", font: "Arial", size: 20, color: "C8DAE8" })]
                  }),  // "—  Plain English search — no training, no tech ski..."
                  new Paragraph({
                    children: [new TextRun({ text: "—  ", font: "Arial", size: 22, bold: true, color: "3D8EB9" }), new TextRun({ text: "Named for your business — Pipeline [YourCompany] — it’s yours", font: "Arial", size: 20, color: "C8DAE8" })]
                  }),  // "—  Named for your business — Pipeline [YourCompany..."
                  new Paragraph({
                    children: [new TextRun({ text: "—  ", font: "Arial", size: 22, bold: true, color: "3D8EB9" }), new TextRun({ text: "Runs locally on your computer — your data stays private and secure", font: "Arial", size: 20, color: "C8DAE8" })]
                  }),  // "—  Runs locally on your computer — your data stays..."
                  new Paragraph({
                    children: [new TextRun({ text: "—  ", font: "Arial", size: 22, bold: true, color: "3D8EB9" }), new TextRun({ text: "Hands-on install at a flat rate — fixed scope, fixed price, no surprises", font: "Arial", size: 20, color: "C8DAE8" })]
                  }),  // "—  Hands-on install at a flat rate — fixed scope, ..."
                ]
              }),
            ]
          }),
        ]
      }),
      new Table({  // 1 rows x 1 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [12240],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "1A3A5C", type: ShadingType.CLEAR },
                width: { size: 12240, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({ children: [new TextRun({ text: "" })] }),  // ""
                ]
              }),
            ]
          }),
        ]
      }),
      new Table({  // 1 rows x 2 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [6120, 6120],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "0F2236", type: ShadingType.CLEAR },
                width: { size: 6120, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({
                    children: [new TextRun({ text: "TRUE NORTH DATA STRATEGIES LLC  |  Veteran-Owned Small Business  |  Turning Data into Direction", font: "Arial", size: 14, color: "6B8AA5" })]
                  }),  // "TRUE NORTH DATA STRATEGIES LLC  |  Veteran-Owned S..."
                ]
              }),
              new TableCell({
                borders: thinBorders, shading: { fill: "0F2236", type: ShadingType.CLEAR },
                width: { size: 6120, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({
                    alignment: AlignmentType.RIGHT,
                    children: [new TextRun({ text: "© 2026 True North Data Strategies", font: "Arial", size: 14, color: "6B8AA5" })]
                  }),  // "© 2026 True North Data Strategies"
                ]
              }),
            ]
          }),
        ]
      }),
      new Table({  // 1 rows x 1 cols
        width: { size: 12240, type: WidthType.DXA },
        columnWidths: [12240],
        rows: [
          new TableRow({
            children: [
              new TableCell({
                borders: thinBorders, shading: { fill: "3D8EB9", type: ShadingType.CLEAR },
                width: { size: 12240, type: WidthType.DXA },
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [
                  new Paragraph({ children: [new TextRun({ text: "" })] }),  // ""
                ]
              }),
            ]
          }),
        ]
      }),
    ]
  }]
});

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync("Pipeline_Flyer_REBUILT.docx", buffer);
  console.log("Created: Pipeline_Flyer_REBUILT.docx");
});