"""
Auto-generated python-docx code from: Pipeline_Flyer.docx
Generated by doc_to_code.py - True North Data Strategies

HOW TO RUN:
  pip install python-docx     (one-time)
  python Pipeline_Flyer_generator.py
"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

# ============================================
# COLORS FOUND IN DOCUMENT
# ============================================
COLOR_0F2236 = RGBColor(0x0F, 0x22, 0x36)  # #0F2236
COLOR_1A3A5C = RGBColor(0x1A, 0x3A, 0x5C)  # #1A3A5C
COLOR_3D8EB9 = RGBColor(0x3D, 0x8E, 0xB9)  # #3D8EB9
COLOR_6B8AA5 = RGBColor(0x6B, 0x8A, 0xA5)  # #6B8AA5
COLOR_A0B8CC = RGBColor(0xA0, 0xB8, 0xCC)  # #A0B8CC
COLOR_C8DAE8 = RGBColor(0xC8, 0xDA, 0xE8)  # #C8DAE8
COLOR_FFFFFF = RGBColor(0xFF, 0xFF, 0xFF)  # #FFFFFF

# ============================================
# CREATE DOCUMENT
# ============================================
doc = Document()

# Page setup
section = doc.sections[0]
section.page_width = 7772400
section.page_height = 10058400
section.top_margin = Inches(1.0)
section.bottom_margin = Inches(1.0)
section.left_margin = Inches(1.0)
section.right_margin = Inches(1.0)

# ============================================
# CONTENT
# ============================================

# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
# Cell (0,0) has background color: #3D8EB9


# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "TRUE NORTH DATA STRATEGIES  |  SBA-Certified SDVOSB  |  Colorado Springs, CO"
# Cell (0,0) has background color: #1A3A5C


# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "PIPELINE\n\nYour business already has the answers.\nPipeline connects them.\nPipeline connects your scattered business tools — email, spreadsheets, databases, CRMs, and documents — into one central hu"
# Cell (0,0) has background color: #1A3A5C


# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "SOUND FAMILIAR?"
# Cell (0,0) has background color: #1A3A5C


# Table: 1 rows x 3 cols
table = doc.add_table(rows=1, cols=3)
table.style = "Table Grid"
table.cell(0, 0).text = "Information is everywhere\nClient details in email. Job info in a spreadsheet. Financials in one app. Schedules in another. Nothing talks to each other."
# Cell (0,0) has background color: #1A3A5C
table.cell(0, 1).text = "One person knows everything\nThe owner or office manager is the human search engine. If they’re gone, the team is stuck. Nobody can take a day off."
# Cell (0,1) has background color: #1A3A5C
table.cell(0, 2).text = "You can’t see your own business\nThe data exists, but you can’t get a straight answer without digging through five tools and three people."
# Cell (0,2) has background color: #1A3A5C


# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
# Cell (0,0) has background color: #1A3A5C


# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
table.cell(0, 0).text = "WHAT YOU GET\n—  One hub for all your business data — no more app-hopping\n—  Plain English search — no training, no tech skills needed\n—  Named for your business — Pipeline [YourCompany] — it’s your"
# Cell (0,0) has background color: #1A3A5C


# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
# Cell (0,0) has background color: #1A3A5C


# Table: 1 rows x 2 cols
table = doc.add_table(rows=1, cols=2)
table.style = "Table Grid"
table.cell(0, 0).text = "TRUE NORTH DATA STRATEGIES LLC  |  Veteran-Owned Small Business  |  Turning Data into Direction"
# Cell (0,0) has background color: #0F2236
table.cell(0, 1).text = "© 2026 True North Data Strategies"
# Cell (0,1) has background color: #0F2236


# Table: 1 rows x 1 cols
table = doc.add_table(rows=1, cols=1)
table.style = "Table Grid"
# Cell (0,0) has background color: #3D8EB9


doc.save("Pipeline_Flyer_REBUILT.docx")
print("Created: Pipeline_Flyer_REBUILT.docx")