from .schema import ColumnMapping, ConfigEntryMapping, DatasetMapping, DerivedMapping, TargetAssignment


def assign(collection: str, field: str, transform: str = "identity", required: bool = False, notes: str = "") -> TargetAssignment:
    return TargetAssignment(collection=collection, field=field, transform=transform, required=required, notes=notes)


def column(source_column: str, *assignments: TargetAssignment) -> ColumnMapping:
    return ColumnMapping(source_column=source_column, assignments=tuple(assignments))


def ignore(source_column: str, reason: str) -> ColumnMapping:
    return ColumnMapping(source_column=source_column, ignore=True, ignore_reason=reason)


def derive(source_columns: tuple[str, ...], collection: str, field: str, transform: str, required: bool = False, notes: str = "") -> DerivedMapping:
    return DerivedMapping(
        source_columns=source_columns,
        collection=collection,
        field=field,
        transform=transform,
        required=required,
        notes=notes,
    )


DATASET_MAPPINGS: tuple[DatasetMapping, ...] = (
    DatasetMapping(
        key="csv:COLORADO CONTACTS.csv",
        kind="csv",
        source_path="databases/COLORADO CONTACTS.csv",
        merge_key="reference_contacts.referenceContactId",
        notes="Reference contacts for compliance and operations.",
        column_mappings=(
            column("Organization", assign("reference_contacts", "organization", required=True)),
            column("Department", assign("reference_contacts", "department")),
            column("Phone Number", assign("reference_contacts", "phoneNumber")),
            column("Address", assign("reference_contacts", "address")),
            column("Website", assign("reference_contacts", "website", transform="normalize_url")),
            column("Contact Purpose", assign("reference_contacts", "contactPurpose")),
            column("Hours", assign("reference_contacts", "hours")),
            column("Notes", assign("reference_contacts", "notes")),
        ),
        derived_mappings=(
            derive(("Organization", "Department"), "reference_contacts", "referenceContactId", "slug_concat"),
            derive(tuple(), "reference_contacts", "orgId", "literal:example-fleet-co"),
            derive(("Department", "Contact Purpose"), "reference_contacts", "category", "infer_reference_contact_category"),
        ),
    ),
    DatasetMapping(
        key="csv:EMERGENCY CONTACTS.csv",
        kind="csv",
        source_path="databases/EMERGENCY CONTACTS.csv",
        merge_key="emergency_contacts.contactId",
        notes="Emergency vendors and response contacts.",
        column_mappings=(
            column("Contact Type", assign("emergency_contacts", "contactType")),
            column("Organization/Person", assign("emergency_contacts", "displayName", required=True)),
            column("Primary Phone", assign("emergency_contacts", "primaryPhone")),
            column("Secondary Phone", assign("emergency_contacts", "secondaryPhone")),
            column("24/7 Available", assign("emergency_contacts", "is24x7Available", transform="normalize_yes_no")),
            column("Email", assign("emergency_contacts", "email", transform="lowercase_email")),
            column("Address", assign("emergency_contacts", "address")),
            column("Contact Person", assign("emergency_contacts", "contactPerson")),
            column("Services Provided", assign("emergency_contacts", "servicesProvided")),
            column("Response Time", assign("emergency_contacts", "responseTime")),
            column("Notes", assign("emergency_contacts", "notes")),
        ),
        derived_mappings=(
            derive(("Contact Type", "Organization/Person"), "emergency_contacts", "contactId", "slug_concat"),
            derive(tuple(), "emergency_contacts", "orgId", "literal:example-fleet-co"),
        ),
    ),
    DatasetMapping(
        key="csv:EMPLOYEES.csv",
        kind="csv",
        source_path="databases/EMPLOYEES.csv",
        merge_key="people.employeeId",
        notes="Primary employee/driver dataset with duplicated and sensitive fields.",
        column_mappings=(
            column("Employee ID", assign("people", "employeeId", required=True), assign("employee_compliance", "employeeId")),
            column("Last Name", assign("people", "lastName")),
            column("First Name", assign("people", "firstName")),
            ignore("Social Security Number", "Sensitive. Requires backend-only secure storage if kept at all."),
            column("Date of Birth", assign("people", "dob", transform="normalize_date_preferred")),
            column("Hire Date", assign("people", "hireDate", transform="normalize_date"), assign("employee_compliance", "hireDate", transform="normalize_date")),
            column("Job Title", assign("people", "jobTitle")),
            column("Department", assign("people", "department")),
            column("Supervisor", assign("people", "supervisorName")),
            column("Pay Rate", assign("people", "payRate", transform="normalize_currency")),
            column("Work Phone", assign("people", "phone")),
            column("Work Email", assign("people", "email", transform="lowercase_email")),
            column("Emergency Contact Phone", assign("emergency_contacts", "primaryPhone")),
            column("Emergency Contact Relationship", assign("emergency_contacts", "relationship")),
            column("CDL Number", assign("employee_compliance", "cdlNumber")),
            column("CDL Class", assign("employee_compliance", "cdlClass")),
            column("CDL Expiration", assign("employee_compliance", "cdlExpiration", transform="normalize_date")),
            column("Hazmat Endorsement", assign("employee_compliance", "hazmatEndorsement", transform="normalize_yes_no")),
            column("Hazmat Expiration", assign("employee_compliance", "hazmatExpiration", transform="normalize_date")),
            column("Tank Endorsement", assign("employee_compliance", "tankEndorsement", transform="normalize_yes_no")),
            column("Air Brakes Endorsement", assign("employee_compliance", "airBrakesEndorsement", transform="normalize_yes_no")),
            column("Medical Certificate Number", assign("employee_compliance", "medicalCertificateNumber")),
            column("Medical Expiration", assign("employee_compliance", "medicalExpiration", transform="normalize_date")),
            column("Last MVR Check", assign("employee_compliance", "lastMvrCheck", transform="normalize_date")),
            column("Next MVR Due", assign("employee_compliance", "nextMvrDue", transform="normalize_date")),
            column("Last Drug Test", assign("employee_compliance", "lastDrugTest", transform="normalize_date")),
            column("Expiration HAZMAT TRAINING 3 YEAR CERT", assign("employee_compliance", "hazmatTrainingExpiration", transform="normalize_date")),
            column("Last Safety Training", assign("employee_compliance", "lastSafetyTraining", transform="normalize_date")),
            column("Uniform Size", assign("people", "uniformSize")),
            column("Assigned Vehicle", assign("people", "assignedVehicleName")),
            column("COMPANY PHONE", assign("people", "companyPhone")),
            column("DOB", assign("people", "dobAlt", transform="normalize_date_secondary")),
            column("Notes", assign("people", "notes")),
            column("TSA Check Last 5 Years", assign("employee_compliance", "tsaCheckDate", transform="normalize_date")),
            column("TSA Expiration", assign("employee_compliance", "tsaExpiration", transform="normalize_date")),
            column("UE ID", assign("people", "ueId")),
            column("90 Day Review", assign("people", "ninetyDayReviewDate", transform="normalize_date")),
            column("MVR ANNUAL REVIEWS", assign("employee_compliance", "mvrAnnualReviewDate", transform="normalize_date")),
            column("HAZMAT TRAINING 3 YEAR CERT", assign("employee_compliance", "hazmatTrainingCompletedAt", transform="normalize_date")),
        ),
        derived_mappings=(
            derive(("Employee ID",), "people", "personId", "prefix:emp_"),
            derive(("Employee ID",), "employee_compliance", "complianceId", "prefix:comp_"),
            derive(("Employee ID",), "emergency_contacts", "contactId", "prefix:emp_emergency_"),
            derive(tuple(), "people", "orgId", "literal:example-fleet-co"),
            derive(tuple(), "employee_compliance", "orgId", "literal:example-fleet-co"),
            derive(tuple(), "emergency_contacts", "orgId", "literal:example-fleet-co"),
            derive(("First Name", "Last Name"), "people", "fullName", "concat_name", required=True),
            derive(("Date of Birth", "DOB"), "people", "dob", "coalesce_date", notes="Prefer Date of Birth, fallback to DOB."),
            derive(("Employee ID",), "emergency_contacts", "personId", "prefix:emp_"),
            derive(tuple(), "emergency_contacts", "contactType", "literal:employee-emergency"),
        ),
    ),
    DatasetMapping(
        key="csv:MAINTENANCE SCHEDULE.csv",
        kind="csv",
        source_path="databases/MAINTENANCE SCHEDULE.csv",
        merge_key="maintenance_plans.planId",
        notes="Planned maintenance cadence data.",
        column_mappings=(
            column("Unit/Equipment", assign("maintenance_plans", "assetRef")),
            column("Maintenance Type", assign("maintenance_plans", "maintenanceType")),
            column("Frequency", assign("maintenance_plans", "frequency")),
            column("Last Performed", assign("maintenance_plans", "lastPerformed", transform="normalize_date")),
            column("Next Due Date", assign("maintenance_plans", "nextDueDate", transform="normalize_date")),
            column("Next Due Mileage", assign("maintenance_plans", "nextDueMileage", transform="normalize_int")),
            column("Service Provider", assign("maintenance_plans", "serviceProvider")),
            column("Estimated Cost", assign("maintenance_plans", "estimatedCost", transform="normalize_currency")),
            column("Parts Required", assign("maintenance_plans", "partsRequired")),
            column("Labor Hours", assign("maintenance_plans", "laborHours", transform="normalize_float")),
            column("Priority", assign("maintenance_plans", "priority")),
            column("Status", assign("maintenance_plans", "status")),
            column("Work Order Number", assign("maintenance_plans", "workOrderNumber")),
            column("Notes", assign("maintenance_plans", "notes")),
        ),
        derived_mappings=(
            derive(("Unit/Equipment", "Maintenance Type"), "maintenance_plans", "planId", "slug_concat"),
            derive(tuple(), "maintenance_plans", "orgId", "literal:example-fleet-co"),
        ),
    ),
    DatasetMapping(
        key="csv:PERMITS & LICENSES.csv",
        kind="csv",
        source_path="databases/PERMITS & LICENSES.csv",
        merge_key="permit_license_records.recordId",
        notes="Permit and license tracking source for suspense generation.",
        column_mappings=(
            column("Permit Type", assign("permit_license_records", "permitType")),
            column("Permit Number", assign("permit_license_records", "permitNumber")),
            column("Issuing Agency", assign("permit_license_records", "issuingAgency")),
            column("Issue Date", assign("permit_license_records", "issueDate", transform="normalize_date")),
            column("Expiration Date", assign("permit_license_records", "expirationDate", transform="normalize_date")),
            column("Renewal Due Date", assign("permit_license_records", "renewalDueDate", transform="normalize_date")),
            column("Annual Fee", assign("permit_license_records", "annualFee", transform="normalize_currency")),
            column("Responsible Employee", assign("permit_license_records", "responsibleEmployeeName")),
            column("Status", assign("permit_license_records", "status")),
            column("Last Inspection", assign("permit_license_records", "lastInspection", transform="normalize_date")),
            column("Next Inspection", assign("permit_license_records", "nextInspection", transform="normalize_date")),
            column("Compliance Notes", assign("permit_license_records", "complianceNotes")),
            column("Renewal Checklist", assign("permit_license_records", "renewalChecklist")),
            column("Alert Days Before Expiry", assign("permit_license_records", "alertDaysBeforeExpiry", transform="normalize_int")),
        ),
        derived_mappings=(
            derive(("Permit Type", "Permit Number"), "permit_license_records", "recordId", "slug_concat"),
            derive(tuple(), "permit_license_records", "orgId", "literal:example-fleet-co"),
            derive(("Permit Type",), "permit_license_records", "templateId", "match_permit_template"),
            derive(tuple(), "permit_license_records", "entityType", "literal:organization"),
            derive(tuple(), "permit_license_records", "entityId", "literal:example-fleet-co"),
        ),
    ),
    DatasetMapping(
        key="csv:STORAGE TANKS.csv",
        kind="csv",
        source_path="databases/STORAGE TANKS.csv",
        merge_key="tank_assets.tankId",
        notes="Tank inventory and tank-specific compliance dataset.",
        column_mappings=(
            column("Tank ID", assign("tank_assets", "tankId", required=True), assign("assets", "sourceRef")),
            column("Tank Location", assign("tank_assets", "location"), assign("assets", "location")),
            column("Tank Type", assign("tank_assets", "tankType")),
            column("Capacity (Gallons)", assign("tank_assets", "capacityGallons", transform="normalize_int")),
            column("Product Stored", assign("tank_assets", "productStored")),
            column("Installation Date", assign("tank_assets", "installationDate", transform="normalize_date")),
            column("Tank Material", assign("tank_assets", "tankMaterial")),
            column("Manufacturer", assign("tank_assets", "manufacturer")),
            column("Serial Number", assign("tank_assets", "serialNumber")),
            column("UST Permit Number", assign("tank_assets", "ustPermitNumber")),
            column("Permit Expiration", assign("tank_assets", "permitExpiration", transform="normalize_date")),
            column("Last Inspection Date", assign("tank_assets", "lastInspectionDate", transform="normalize_date")),
            column("Inspector", assign("tank_assets", "inspector")),
            column("Next Inspection Due", assign("tank_assets", "nextInspectionDue", transform="normalize_date")),
            column("Leak Detection System", assign("tank_assets", "leakDetectionSystem")),
            column("Last Leak Test", assign("tank_assets", "lastLeakTest", transform="normalize_date")),
            column("Next Leak Test Due", assign("tank_assets", "nextLeakTestDue", transform="normalize_date")),
            column("Spill Containment", assign("tank_assets", "spillContainment", transform="normalize_yes_no")),
            column("Overfill Protection", assign("tank_assets", "overfillProtection", transform="normalize_yes_no")),
            column("Cathodic Protection", assign("tank_assets", "cathodicProtection", transform="normalize_yes_no")),
            column("Groundwater Monitoring", assign("tank_assets", "groundwaterMonitoring", transform="normalize_yes_no")),
            column("Financial Responsibility", assign("tank_assets", "financialResponsibility")),
            column("Insurance Coverage", assign("tank_assets", "insuranceCoverage")),
            column("Current Inventory", assign("tank_assets", "currentInventory", transform="normalize_float")),
            column("Reorder Level", assign("tank_assets", "reorderLevel", transform="normalize_float")),
            column("Maximum Fill", assign("tank_assets", "maximumFill", transform="normalize_float")),
            column("Daily Measurement Time", assign("tank_assets", "dailyMeasurementTime", transform="normalize_time")),
            column("Measuring Device", assign("tank_assets", "measuringDevice")),
            column("Calibration Chart", assign("tank_assets", "calibrationChart")),
            column("Last Calibration", assign("tank_assets", "lastCalibration", transform="normalize_date")),
            column("Next Calibration Due", assign("tank_assets", "nextCalibrationDue", transform="normalize_date")),
            column("Tank Status", assign("tank_assets", "status"), assign("assets", "status")),
            column("Notes", assign("tank_assets", "notes"), assign("assets", "notes")),
        ),
        derived_mappings=(
            derive(("Tank ID",), "tank_assets", "assetId", "prefix:tank_"),
            derive(("Tank ID",), "assets", "assetId", "prefix:tank_"),
            derive(tuple(), "tank_assets", "orgId", "literal:example-fleet-co"),
            derive(tuple(), "assets", "orgId", "literal:example-fleet-co"),
            derive(tuple(), "assets", "category", "literal:tank"),
            derive(("Tank ID",), "assets", "name", "prefix_label:Tank "),
        ),
    ),
    DatasetMapping(
        key="csv:VEHICLES & EQUIPMENT.csv",
        kind="csv",
        source_path="databases/VEHICLES & EQUIPMENT.csv",
        merge_key="vehicle_assets.unitNumber",
        notes="Vehicle and equipment source dataset.",
        column_mappings=(
            column("Unit Number", assign("vehicle_assets", "unitNumber", required=True), assign("assets", "sourceRef")),
            column("Vehicle Type", assign("vehicle_assets", "vehicleType"), assign("assets", "category", transform="normalize_vehicle_category")),
            column("Year", assign("vehicle_assets", "year", transform="normalize_int")),
            column("Make", assign("vehicle_assets", "make")),
            column("Model", assign("vehicle_assets", "model")),
            column("VIN", assign("vehicle_assets", "vin", transform="uppercase")),
            column("License Plate", assign("vehicle_assets", "licensePlate", transform="uppercase")),
            column("Registration Expiration", assign("vehicle_assets", "registrationExpiration", transform="normalize_date")),
            column("Insurance Policy Number", assign("vehicle_assets", "insurancePolicyNumber")),
            column("Insurance Expiration", assign("vehicle_assets", "insuranceExpiration", transform="normalize_date")),
            column("Tank Capacity (Gallons)", assign("vehicle_assets", "tankCapacityGallons", transform="normalize_float")),
            column("Number of Compartments", assign("vehicle_assets", "compartmentCount", transform="normalize_int")),
            column("Pump System", assign("vehicle_assets", "pumpSystem")),
            column("Meter System", assign("vehicle_assets", "meterSystem")),
            column("Hose Length", assign("vehicle_assets", "hoseLength")),
            column("Current Mileage", assign("vehicle_assets", "currentMileage", transform="normalize_int")),
            column("Last Oil Change", assign("vehicle_assets", "lastOilChange", transform="normalize_date")),
            column("Last Oil Change Mileage", assign("vehicle_assets", "lastOilChangeMileage", transform="normalize_int")),
            column("Next Oil Change Due", assign("vehicle_assets", "nextOilChangeDue", transform="normalize_date")),
            column("Next Oil Change Mileage", assign("vehicle_assets", "nextOilChangeMileage", transform="normalize_int")),
            column("Last DOT Inspection", assign("vehicle_assets", "lastDotInspection", transform="normalize_date")),
            column("Next DOT Inspection Due", assign("vehicle_assets", "nextDotInspectionDue", transform="normalize_date")),
            column("DOT Inspection Certificate", assign("vehicle_assets", "dotInspectionCertificateRef")),
            column("Last Vapor Test", assign("vehicle_assets", "lastVaporTest", transform="normalize_date")),
            column("Next Vapor Test Due", assign("vehicle_assets", "nextVaporTestDue", transform="normalize_date")),
            column("Vapor Test Certificate", assign("vehicle_assets", "vaporTestCertificateRef")),
            column("CDL Required", assign("vehicle_assets", "cdlRequired", transform="normalize_yes_no")),
            column("Hazmat Required", assign("vehicle_assets", "hazmatRequired", transform="normalize_yes_no")),
            column("Assigned Driver", assign("vehicle_assets", "assignedDriverName")),
            column("Backup Driver", assign("vehicle_assets", "backupDriverName")),
            column("GPS Unit ID", assign("vehicle_assets", "gpsUnitId")),
            column("Radio Unit Number", assign("vehicle_assets", "radioUnitNumber")),
            column("Fuel Card Number", assign("vehicle_assets", "fuelCardNumber")),
            column("EZ Pass Number", assign("vehicle_assets", "ezPassNumber")),
            column("Purchase Date", assign("vehicle_assets", "purchaseDate", transform="normalize_date"), assign("assets", "purchaseDate", transform="normalize_date")),
            column("Purchase Price", assign("vehicle_assets", "purchasePrice", transform="normalize_currency"), assign("assets", "purchasePrice", transform="normalize_currency")),
            column("Current Book Value", assign("vehicle_assets", "currentBookValue", transform="normalize_currency")),
            column("Maintenance Schedule", assign("vehicle_assets", "maintenanceScheduleName")),
            column("Last Major Repair", assign("vehicle_assets", "lastMajorRepair", transform="normalize_date_or_text")),
            column("Next Service Due", assign("vehicle_assets", "nextServiceDue", transform="normalize_date")),
            column("Vehicle Status", assign("vehicle_assets", "status"), assign("assets", "status")),
            column("Location", assign("vehicle_assets", "location"), assign("assets", "location")),
            column("Notes", assign("vehicle_assets", "notes"), assign("assets", "notes")),
        ),
        derived_mappings=(
            derive(("Unit Number",), "vehicle_assets", "assetId", "identity"),
            derive(("Unit Number",), "assets", "assetId", "identity"),
            derive(tuple(), "vehicle_assets", "orgId", "literal:example-fleet-co"),
            derive(tuple(), "assets", "orgId", "literal:example-fleet-co"),
            derive(("Year", "Make", "Model"), "assets", "name", "compose_vehicle_name"),
        ),
    ),
    DatasetMapping(
        key="worksheet:Assets Master",
        kind="worksheet",
        source_path="asset-command_vs.001/asset-command-working-testing-03-07-2026.xlsx",
        worksheet="Assets Master",
        merge_key="assets.assetId",
        notes="Fleet-Compliance Sentinel asset master sheet. Operational asset summary data.",
        column_mappings=(
            column("Asset ID", assign("assets", "assetId", required=True)),
            column("Asset Name", assign("assets", "name")),
            column("Asset Type", assign("assets", "category")),
            column("Status", assign("assets", "status")),
            column("Current Location", assign("assets", "location")),
            column("Assigned To", assign("assets", "assignedToName")),
            column("Last Service Date", assign("assets", "lastServiceDate", transform="normalize_date")),
            column("Next Service Due", assign("assets", "nextServiceDue", transform="normalize_date")),
            column("Service Interval (Days)", assign("assets", "serviceIntervalDays", transform="normalize_int")),
            column("Acquisition Date", assign("assets", "purchaseDate", transform="normalize_date")),
            column("Acquisition Cost", assign("assets", "purchasePrice", transform="normalize_currency")),
            column("Notes", assign("assets", "notes")),
        ),
        derived_mappings=(
            derive(tuple(), "assets", "orgId", "literal:example-fleet-co"),
        ),
    ),
    DatasetMapping(
        key="worksheet:Drivers",
        kind="worksheet",
        source_path="asset-command_vs.001/asset-command-working-testing-03-07-2026.xlsx",
        worksheet="Drivers",
        merge_key="employee_compliance.driverId",
        notes="Fleet-Compliance Sentinel driver sheet with operational compliance fields.",
        column_mappings=(
            column("Driver ID", assign("people", "employeeId"), assign("employee_compliance", "driverId", required=True)),
            column("Driver Name", assign("people", "fullName")),
            column("Status", assign("employee_compliance", "employmentStatus")),
            column("Phone", assign("people", "phone")),
            column("Email", assign("people", "email", transform="lowercase_email")),
            column("License Number", assign("employee_compliance", "licenseNumber")),
            column("License State", assign("employee_compliance", "licenseState")),
            column("License Expiry", assign("employee_compliance", "licenseExpiration", transform="normalize_date")),
            column("License Type", assign("employee_compliance", "licenseType")),
            column("CDL Number", assign("employee_compliance", "cdlNumber")),
            column("CDL Expiry", assign("employee_compliance", "cdlExpiration", transform="normalize_date")),
            column("CDL Endorsements", assign("employee_compliance", "cdlEndorsements", transform="split_csv")),
            column("Medical Card Expiry", assign("employee_compliance", "medicalExpiration", transform="normalize_date")),
            column("Medical Examiner", assign("employee_compliance", "medicalExaminer")),
            column("Medical Exam Date", assign("employee_compliance", "medicalExamDate", transform="normalize_date")),
            column("Background Check Date", assign("employee_compliance", "backgroundCheckDate", transform="normalize_date")),
            column("Clearinghouse Status", assign("employee_compliance", "clearinghouseStatus")),
            column("MVR Review Date", assign("employee_compliance", "mvrReviewDate", transform="normalize_date")),
            column("Drug Test Date", assign("employee_compliance", "lastDrugTest", transform="normalize_date")),
            column("Drug Test Result", assign("employee_compliance", "drugTestResult")),
            column("Last HOS Audit", assign("employee_compliance", "lastHosAudit", transform="normalize_date")),
            column("ELD Provider", assign("employee_compliance", "eldProvider")),
            column("ELD Device ID", assign("employee_compliance", "eldDeviceId")),
            column("ELD Compliant", assign("employee_compliance", "eldCompliant", transform="normalize_yes_no")),
            column("Last Pre-Trip Date", assign("employee_compliance", "lastPreTripDate", transform="normalize_date")),
            column("Last Post-Trip Date", assign("employee_compliance", "lastPostTripDate", transform="normalize_date")),
            column("Annual Inspection Due", assign("employee_compliance", "annualInspectionDue", transform="normalize_date")),
            column("Hire Date", assign("people", "hireDate", transform="normalize_date"), assign("employee_compliance", "hireDate", transform="normalize_date")),
            column("Termination Date", assign("people", "terminationDate", transform="normalize_date")),
            column("Notes", assign("people", "notes"), assign("employee_compliance", "notes")),
        ),
        derived_mappings=(
            derive(("Driver ID",), "people", "personId", "prefix:emp_"),
            derive(("Driver ID",), "employee_compliance", "complianceId", "prefix:comp_"),
            derive(tuple(), "people", "orgId", "literal:example-fleet-co"),
            derive(tuple(), "employee_compliance", "orgId", "literal:example-fleet-co"),
        ),
    ),
    DatasetMapping(
        key="worksheet:Activity Log",
        kind="worksheet",
        source_path="asset-command_vs.001/asset-command-working-testing-03-07-2026.xlsx",
        worksheet="Activity Log",
        merge_key="activity_logs.activityId",
        notes="Operational asset event log.",
        column_mappings=(
            column("Timestamp", assign("activity_logs", "timestamp", transform="normalize_datetime")),
            column("Asset ID", assign("activity_logs", "assetId", required=True)),
            column("Asset Name", assign("activity_logs", "assetName")),
            column("Action Type", assign("activity_logs", "actionType")),
            column("Employee", assign("activity_logs", "employeeName")),
            column("Location", assign("activity_logs", "location")),
            column("Odometer/Hours", assign("activity_logs", "meterReading", transform="normalize_float")),
            column("Fuel Added (gal)", assign("activity_logs", "fuelAddedGallons", transform="normalize_float")),
            column("Fuel Cost", assign("activity_logs", "fuelCost", transform="normalize_currency")),
            column("Condition Notes", assign("activity_logs", "notes")),
        ),
        derived_mappings=(
            derive(("Timestamp", "Asset ID", "Action Type"), "activity_logs", "activityId", "slug_concat"),
            derive(tuple(), "activity_logs", "orgId", "literal:example-fleet-co"),
        ),
    ),
    DatasetMapping(
        key="worksheet:Maintenance Tracker",
        kind="worksheet",
        source_path="asset-command_vs.001/asset-command-working-testing-03-07-2026.xlsx",
        worksheet="Maintenance Tracker",
        merge_key="maintenance_events.maintenanceEventId",
        notes="Executed maintenance event log from Fleet-Compliance Sentinel.",
        column_mappings=(
            column("Maintenance ID", assign("maintenance_events", "maintenanceEventId", required=True)),
            column("Asset ID", assign("maintenance_events", "assetId")),
            column("Asset Name", assign("maintenance_events", "assetName")),
            column("Service Type", assign("maintenance_events", "serviceType")),
            column("Scheduled Date", assign("maintenance_events", "scheduledDate", transform="normalize_date")),
            column("Completed Date", assign("maintenance_events", "completedDate", transform="normalize_date")),
            column("Status", assign("maintenance_events", "status")),
            column("Parts Cost", assign("maintenance_events", "partsCost", transform="normalize_currency")),
            column("Labor Cost", assign("maintenance_events", "laborCost", transform="normalize_currency")),
            column("Total Cost", assign("maintenance_events", "totalCost", transform="normalize_currency")),
            column("Vendor", assign("maintenance_events", "vendor")),
            column("Invoice Number", assign("maintenance_events", "invoiceNumber")),
            column("Notes", assign("maintenance_events", "notes")),
        ),
        derived_mappings=(
            derive(tuple(), "maintenance_events", "orgId", "literal:example-fleet-co"),
        ),
    ),
    DatasetMapping(
        key="worksheet:Config",
        kind="config_sheet",
        source_path="asset-command_vs.001/asset-command-working-testing-03-07-2026.xlsx",
        worksheet="Config",
        merge_key="organizations.orgId",
        notes="Fleet-Compliance Sentinel key/value config sheet.",
        column_mappings=(
            column("Setting"),
            column("Value"),
        ),
        config_entry_mappings=(
            ConfigEntryMapping("Business Name", assign("organizations", "name")),
            ConfigEntryMapping("Email Address", assign("organizations", "alertEmail", transform="lowercase_email")),
            ConfigEntryMapping("Alert Threshold (days)", assign("organizations", "settings.defaultAlertDays", transform="single_alert_day")),
            ConfigEntryMapping("Fuel Anomaly Threshold (%)", assign("organizations", "settings.fuelAnomalyThresholdPct", transform="normalize_float")),
        ),
        derived_mappings=(
            derive(tuple(), "organizations", "orgId", "literal:example-fleet-co"),
            derive(tuple(), "organizations", "timezone", "literal:America/Denver"),
        ),
    ),
)


DATASET_MAPPINGS_BY_KEY = {dataset.key: dataset for dataset in DATASET_MAPPINGS}
